.TH ammsc 1 "August 3, 2012" "1.9" "An account management system for SQUID"

.SH НАЗВАНИЕ
ammsc \- консольный клиент amms

.SH СИНТАКСИС
.B ammsc
.RI команда
аргументы
.br

.SH ОПИСАНИЕ
AMMS клиент реализует запросы по протоколу HTTP, обеспечивает синтаксис управления лимитами и расширениями ammsd.
Распределение запросов, аутентификацию и прочие дополнительные возможности реализует высокопроизводительный http сервер.
Допускается сокращенное написание команды и аргументов, если они не конфликтуют с другими.
Командой является имя расширения или встроенные в ammsc команды.

.SH ВСТРОЕННЫЕ КОМАНДЫ
.B limit
[ident] [V|no|state|desc|parent|rename|over] [P|no] [t|i|p]
.RS

ident - идентификатор пользователя, V - объем трафика (Б,КБ,МБ,ГБ), P - период (s/m/h/d - сек/мин/час/день)

Установить лимит пользователя user1, 100M на 24 часа с начала суток (таймер abs), с времени задания лимита (таймер rel)

	ammsc li user1 100M 1d

Если тип лимита не указан, подразумевается ident.

Удалить лимит:

	ammsc li user1 no

Задать описание:

	ammsc li user1 desc SuperUser

Удалить описание:

	ammsc li user1 desc no

Изменить статус (включен, выключен, заблокирован):

	ammsc li user1 s on|off|dis

Назначить родительский лимит (наследование недостающих параметров):

	ammsc li user1 parent users

Переименовать user1 в user2:

	ammsc li user1 ren user2

Задать неограниченный лимит на опр. период:

	ammsc li user1 over 3d

Удалить неограниченный лимит вручную:

	ammsc li user1 over no

Формат вывода:

     тип_лимита идентификатор родитель значение_лимита временной_период состояние_лимита unixtime дата время описание

.RE

.B reset
ident
.RS
Сброс трафика
.RE

.B stat
ident

.RS
Объем использованного трафика за период действия лимита
ident - идентификатор пользователя, если не указан выводится
статистика по всем пользователям

Формат вывода:

    тип_лимита идентификатор родитель трафик трафик_кэш значение_лимита временной_период состояние_лимита unixtime дата время описание
.RE

.B ext
.RS
Список расширений
.RE

.SH РАСШИРЕНИЯ
.B bind
[ls|set ident ip|rem num|get ident|check ident ip]

.RS
 Привязка логина к IP адресу
 ls - просмотр таблицы
 set - установка привязки ident к ip
 rem num - удалить запись с номером num
 get ident - получить записи для ident
 check ident ip - проверить доступ по ident и ip
.RE

.B history
ident [date] [count]

.RS
 Лог пользователя за определенную дату
 ident - идентификатор пользователя
 date - дата, если не указано - текущий день

 Формат даты (date): YYYYMMDD, "YYYYMMDD HHMMSS"
 t[oday] - сегодняшняя дата
 y[esterday] - вчерашняя дата
 yy - позавчера
 yyy - позапозавчера и т.д.
.RE

.B ip
ident [date]

.RS
 IP адреса пользователя за определенную дату
 ident - идентификатор пользователя
 date - дата
.RE

.B log
ident [count]

.RS
 Лог трафика пользователя
 ident - идентификатор пользователя
 count - количество выводимых строк (по умолчанию 50)
.RE

.B traf
ident date

.RS
 Объем трафика пользователя за временной период
 ident - идентификатор пользователя ( . - статистика по всем пользователям )
 date - дата
.RE

.B uri
ident date [detail]

.RS
 Объем трафика пользователя по URL за временной период
 ident - идентификатор пользователя
 date - дата
 detail - детализация
.RE


.SH "СМОТРИТЕ ТАКЖЕ"

