#!/usr/bin/perl

# AMMS redirector for squid
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
	    
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
			    
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use lib '/usr/lib/amms';
use AMMS::Client;
use Config::General;
use Getopt::Long;

use strict;

my $config_file;
my $profile;
my %config;

GetOptions ("config|c=s" => \$config_file, "profile|p=s" => \$profile);

sub load_config {

    $config_file ||= "/etc/amms.conf";
    $profile ||= "default";
    %config = Config::General::ParseConfig (-ConfigFile => $config_file, -InterPolateVars => 1);

    unless (exists $config {$profile}){
        die "Unknown profile name: $profile";
    }
}

my $ammsd_uri = $config{$profile}{ammsrd}{ammsd_uri};
my $hashd_uri = $config{$profile}{ammsrd}{hashd_uri};

my $ammsc = AMMS::Client->new;
unless ($ammsc->connect ($ammsd_uri)){
    undef $ammsc;
}

my $hashd = AMMS::Client->new;
unless ($hashd->connect ($hashd_uri)){
    undef $hashd;
}

undef $hashd if $config{$profile}{ammsrd}{ip_as_ident};

$|=1;

my @f;
my ($ident, $ip, $res);

while (<>) {

    unless (defined $ammsc){
        print $config{$profile}{ammsrd}{t_interr} . "\n";
        next;
    }

    my @f = split (/\s/);

    $ip = substr ($f [1], 0, -2);

    $ident = $f [2];
    $ident = $ip if ($config{$profile}{ammsrd}{ip_as_ident});
    
    if ($hashd){

        $res = $hashd->exe ("check2", "squid", "lock", $ident, $ip);

        if ($res !~ /OK/i){
            print $config{$profile}{ammsrd}{t_denybyip} . "\n";
            next;
        }
    }

    $res = $ammsc->exe ("check_access", "squid", $ident);

    if ($res =~ /OK/i){
        print "\n";
        next;
    }

    if ($ammsc->{err_desc} =~ /sys/){
        print $config{$profile}{ammsrd}{t_overlim} . "\n";
        next;
    }

    print "http://localhost/deny.html\n";
}

