#!/usr/bin/perl

use strict;

use DBI;
use Config::General;
use Getopt::Long;

my %config;
my ($profile, $config_file);

sub load_config {
    
    $config_file ||= '/etc/ammsd.conf';

    %config = ();    
    %config = Config::General::ParseConfig (-ConfigFile => $config_file, -InterPolateVars => 1);
    
    my $keys_count = scalar keys (%config);
    
    unless ($keys_count){
	    die "Bad configuration in $config_file";
    }

    return $keys_count;
}

GetOptions ("profile|p=s" => \$profile, "config|c=s" => \$config_file);
load_config ();

my $file = $ARGV [0];

open (FH, "<$file") || die "Can't open $file ($!)";

my $dbh = DBI->connect ($config {$profile}{db}{dsn}, $config {$profile}{db}{user}, $config{$profile}{db}{pass},
                       {RaiseError => 1, PrintError => 1, AutoCommit => 1});

my (@f, $i, $added);

while (<FH>){

    @f = split (/\s+/);

    $i=0;

    for (@f){
        $f [$i] = "" if ($f [$i] eq "-");
        $i++;
    }
    $f [6] = ""; # ts
    $f [7] = $f [8]; # desc
    
    $dbh->do ("insert into lim(`type`,`ident`,`parent`,`value`,`period`,`stat`,`ts`,`desc`) values(?,?,?,?,?,?,?,?)",
               undef, @f) && $added++;
}

$dbh->disconnect;
close FH;

if ($added){
    print "OK $added\n";
    exit;
}

print "ERR Nothing added";

