#!/usr/bin/perl

use strict;

use lib "/usr/lib/amms/";
use AMMS::Lib qw(locate fdate);
use File::Which;

my ($ident, $date) = @ARGV;

die "No ident" unless $ident;

$date ||= "today";

my $user_log = locate ($ident, "log");
my $date = fdate ($date);

my $grep = which ("grep");
my $sort = which ("sort");
my $cut  = which ("cut");

print `$grep $date $user_log | $cut -d " " -f 3 | $sort -u`;


