#!/usr/bin/perl

use strict;

use lib "/usr/lib/amms/";
use AMMS::Lib qw(locate fdate);
use File::Which;

my ($ident, $count) = @ARGV;

die "No ident" unless $ident;

$count ||= 50;

my $user_log = locate ($ident, "log");
my $tail = which ("tail");

print `$tail -n $count $user_log`;
