#!/usr/bin/perl

use strict;

use DBI;
use Config::General;
use Getopt::Long;

my %config;
my ($profile, $config_file);

sub load_config {
    
    $config_file ||= '/etc/amms.conf';

    %config = ();    
    %config = Config::General::ParseConfig (-ConfigFile => $config_file, -InterPolateVars => 1);
    
    my $keys_count = scalar keys (%config);
    
    unless ($keys_count){
        die "Bad configuration in $config_file";
    }

    return $keys_count;
}

GetOptions ("profile|p=s" => \$profile, "config|c=s" => \$config_file);
load_config ();

my $dbh = DBI->connect ($config {$profile}{db}{dsn}, $config {$profile}{db}{user}, $config{$profile}{db}{pass},
                       {RaiseError => 1, PrintError => 1, AutoCommit => 1});

my ($ident, $date, $detail) = @ARGV;
my @val;

if ($date =~ /to*d*a*y*/i){

    my @tm = localtime (time);
    $date = sprintf ("%04d-%02d-%02d", $tm[5]+1900, $tm[4]+1, $tm[3]);
}

if ($ident eq '.') {

    $dbh->do ("create temporary table th0 (index (ident)) select ident,size from tlog where ts regexp ?
               and (method='GET' or method='CONNECT') and hit=0", undef, $date);

    $dbh->do ("create temporary table th1 (index (ident)) select ident,size from tlog where ts regexp ?
               and (method='GET' or method='CONNECT') and hit=1", undef, $date);

    my $ident = $dbh->selectcol_arrayref ("select distinct ident from th0");

    my @size;
    my $desc;

    for (@$ident){

        @size = ();
        $desc = '';

        $desc = $dbh->selectrow_array ("select `desc` from lim where ident=?", undef, $_);

        $size [2] = $dbh->selectrow_array ("select sum(size) from th0 where ident=?", undef, $_) || '0';
        $size [3] = $dbh->selectrow_array ("select sum(size) from th1 where ident=?", undef, $_) || '0';

        $size [0] = kmg ($size [2]) || '0';
        $size [1] = kmg ($size [3]) || '0';

        printf ("%-16s %7s %7s %12s %12s %s\n", $_, @size, $desc);
    }

    $size [2] = $dbh->selectrow_array ("select sum(size) from th0") || '0';
    $size [3] = $dbh->selectrow_array ("select sum(size) from th1") || '0';

    $size [0] = kmg ($size [2]) || '0';
    $size [1] = kmg ($size [3]) || '0';

    printf ("\n%-16s %7s %7s %12s %12s\n", "Total", @size);

    $dbh->do ("drop table th0, th1");
    exit;
}

if ($detail){

    my $rec = $dbh->selectall_arrayref ("select url,size from tlog where ident=? 
                                         and ts REGEXP ? 
                                         and (method='GET' or method='CONNECT') 
                                         and hit=0 order by size desc", undef, $ident, $date);
    for (@$rec){
        @val = @{$_};
        $val [1] = kmg ($val [1]);
        printf ("%6s %s\n", $val [1], $val [0]);
    }
}
else {

    @val = $dbh->selectrow_array ("select sum(size) from tlog where ident=? and ts REGEXP ? and (method='GET' or method='CONNECT') and hit=0",
                                   undef,  $ident, $date);
    my $size = kmg ($val [0]);
    print $size;
}

sub kmg { # human readable values
    
    my $bytes = shift;
    my $value = $bytes;
            
    my $g = 1073741824;
    my $m = 1048576;
    my $k = 1024;
                        
    if ($bytes >= $g){
        $value = sprintf ('%.2f%s', $bytes / $g, 'G');
    }
    elsif ($bytes >= $m){
        $value = sprintf ('%.1f%s', $bytes / $m, 'M');
    }
    elsif ($bytes >= $k){
        $value = sprintf ('%.1f%s', $bytes / $k, 'K');
    }
    
    $value =~ s/\.0+\s/ /g;
    
    return $value;
}

