#!/bin/sh

### BEGIN INIT INFO
# Provides:          amms
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Should-Start:      nginx apache2 squid
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the amms server
# Description:       starts the amms server
### END INIT INFO

AMMSPATH=/usr/lib/amms
NAME=amms
DESC=amms

CONF=/etc/amms/amms.conf

set -e

[ -x "$AMMSPATH/ammsd" ] || exit 0

case "$1" in
	start)
		case "$2" in
			ammsd)
				echo -n "Starting $2: "
				$AMMSPATH/ammsd -c $CONF start
				;;
			ammsed)
				echo -n "Starting $2: "
				$AMMSPATH/ammsed -c $CONF start
				;;
			hashd)
				echo -n "Starting $2: "
				$AMMSPATH/hashd -c $CONF start
				;;
			tc)
				echo -n "Starting $2: "
				$AMMSPATH/ammstc -c $CONF start
				;;
			*)
				echo "Starting all amms daemons"
				echo -n "ammsd: "
                                $AMMSPATH/ammsd -c $CONF start
				echo -n "ammsed: "
				$AMMSPATH/ammsed -c $CONF start
				echo -n "hashd: "
				$AMMSPATH/hashd -c $CONF start
				echo -n "tc: "
				$AMMSPATH/ammstc -c $CONF start
				;;
		esac
		;;

	stop)
		case "$2" in
			ammsd)
				echo -n "Stopping $2: "
				$AMMSPATH/ammsd -c $CONF stop
				;;
			ammsed)
				echo -n "Stopping $2: "
				$AMMSPATH/ammsed -c $CONF stop
				;;
			hashd)
				echo -n "Stopping $2: "
				$AMMSPATH/hashd -c $CONF stop
				;;
			tc)
				echo -n "Stopping $2: "
				$AMMSPATH/ammstc -c $CONF stop
				;;
			*)
				echo "Stopping all amms daemons"
                                echo -n "tc: "
				$AMMSPATH/ammstc -c $CONF stop
                                echo -n "hashd: "
				$AMMSPATH/hashd -c $CONF stop
                                echo -n "ammsed: "
				$AMMSPATH/ammsed -c $CONF stop
                                echo -n "ammsd: "
				$AMMSPATH/ammsd -c $CONF stop
				;;
		esac
		;;

	restart|force-reload)

                $AMMSPATH/ammsd -c $CONF check || exit $?

		case "$2" in
			ammsd)
				echo -n "Restarting $2: "
				$AMMSPATH/ammsd -c $CONF restart
				;;
			ammsed)
				echo -n "Restarting $2: "
				$AMMSPATH/ammsed -c $CONF restart
				;;
			hashd)
				echo -n "Restarting $2: "
				$AMMSPATH/hashd -c $CONF restart
				;;
			tc)
				echo -n "Restarting $2: "
				$AMMSPATH/ammstc -c $CONF restart
				;;
			*)
				echo "Restarting all amms daemons"
                                echo -n "ammsd: "
				$AMMSPATH/ammsd -c $CONF restart
                                echo -n "ammsed: "
				$AMMSPATH/ammsed -c $CONF restart
                                echo -n "hashd: "
				$AMMSPATH/hashd -c $CONF restart
                                echo -n "tc: "
				$AMMSPATH/ammstc -c $CONF restart
				;;
		esac
		;;

	status)
		case "$2" in
			ammsd)
				echo -n "$2 status: "
				$AMMSPATH/ammsd -c $CONF status
				;;
			ammsed)
				echo -n "$2 status: "
				$AMMSPATH/ammsed -c $CONF status
				;;
			hashd)
				echo -n "$2 status: "
				$AMMSPATH/hashd -c $CONF status
				;;
			tc)
				echo -n "$2 status: "
				$AMMSPATH/ammstc -c $CONF status
				;;
			*)
				echo -n "ammsd: "
				$AMMSPATH/ammsd -c $CONF status
				echo -n "ammsed: "
				$AMMSPATH/ammsed -c $CONF status
				echo -n "hashd: "
				$AMMSPATH/hashd -c $CONF status
				echo -n "ammstc: "
				$AMMSPATH/ammstc -c $CONF status
				;;
		esac
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
