.TH ammsc 1 "August 3, 2012" "1.9" "An account management system for SQUID"

.SH NAME
ammsc \- amms console client

.SH SYNOPSIS
.B ammsc
.RI command
arguments
.br

.SH DESCRIPTION
The AMMS client implements requests by the HTTP protocol for the limit and extensions management.
The distribution of request, authentication and other additional possibilities provides a high performance http server.
The command is extension name or ammsc built-in command.
The syntax supports cisco-like abbreviation of commands and arguments if no conflicts with other names.

.SH Built-in commands
.B limit
[ident] [V|no|state|desc|parent|rename|over] [P|no] [t|i|p]
.RS

ident - user identificator, V - traffic amount (KB,MB,GB), P - period (m/h/d - min/hour/day)

Set user limit for user1, 100M to 24 hr from day begin (timer is abs), from the time of limit setting (the timer is rel)

	ammsc li user1 100M 1d

Default limit type is ident.

Remove limit:

	ammsc li user1 no

Set description:

	ammsc li user1 desc SuperUser

Remove description:

	ammsc li user1 desc no

Change status (on, off, disabled):

	ammsc li user1 s on|off|dis

Set parent limit (parameters inheritance):

	ammsc li user1 parent users

Rename user1 to user2:

	ammsc li user1 ren user2

Set overlimit for specified period, example 3 days:

	ammsc li user1 over 3d

Remove overlimit by hand:

	ammsc li user1 over no

Output format:

     limit_type ident parent limit_value period limit_state unixtime date time description

.RE

.B reset
ident
.RS
Reset traffic
.RE

.B stat
ident

.RS
The volume of traffic used for the period of the limit

ident - user id, default - all users

Output format:

    limit_type ident parent traffic traffic_cached limit_value period limit_state unixtime date time description
.
.RE

.B ext
.RS
Extensions list
.RE

.SH EXTENSIONS
.B bind
[ls|set ident ip|rem num|get ident|check ident ip]

.RS
 Bind login to the specified IP, logins from other IPs disabled.

 ls - view
 set - link ident to ip
 rem num - remove record with number num
 get ident - get records for ident
 check ident ip - check access by ident and ip
.RE

.B history
ident [date]

.RS
 The history of visited sites

 ident - user id
 date - date, default is today

 Date format (date): YYYYMM, "YYYYMMDD HHMMSS"
 t[oday] - today date
 y[esterday] - yesterday date
 yy[esterday] - the day before yesterday
 yyy[esterday] - two days before yesterday, and so on
.RE

.B ip
ident [date]

.RS
 The user IP addresses for the specified period
 
 ident - user id
 date - date
.RE

.B log
ident [count]

.RS
 The tail of user log
 
 ident - user id
 count - output lines count (default is 50)
.RE

.B perf
[reset]

.RS
 Performance and other info about the running ammsd
 
 rpsmax  - max count of requests per second
 rpsavg  - average count of requests per second 
 rcount  - total count of requests
 in      - bytes in
 out     - bytes out
 msmtime - measurement time (the time format is: dd:hh:mm:ss)
 dbsize  - size of the amms data (bytes)
 lcount  - the count of the limits
 uptime  - ammsd uptime (the time format is the same as in msmtime)
.RE

.B traf
ident [date]

.RS
 The volume of traffic used for specified period
 
 ident - user id, default - all users
 date - date
.RE

.B uri
ident [date] [detail]

.RS
 The volume of traffic by URL used for specified period
 
 ident - user id
 date - date
 detail - detailed information
.RE

.SH "SEE ALSO"

